#application.yml
server:
  port: 3080
  ssl:
    key-store: xxr.p12 #自签证书
    key-store-password: 
    key-store-type: PKCS12
    enabled: true

spring:
  application:
    name: uaa


  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meeting?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 数据库密码


# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 72000
  #代表最低活跃频率，单位/秒，例如将其配置为 1800 (30分钟)，代表用户如果30分钟无操作，则此Token会立即过期（被冻结，但不会删除掉）。
  active-timeout: 3600
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # OAuth2.0 配置
  #  # 是否从cookie中读取token
  is-read-cookie: false
  #  # 是否从head中读取token
  is-read-header: true
  #  #能否写入到heard中
  is-write-header: true


  oauth2:
    # 是否打开模式：授权码（Authorization Code）
    is-code: true
    # 是否打开模式：隐藏式（Implicit）
    is-implicit: true
    # 是否打开模式：密码式（Password）
    is-password: true
    # 是否打开模式：凭证式（Client Credentials）
    is-client: false
    # 是否在每次 Refresh-Token 刷新 Access-Token 时，产生一个新的 Refresh-Token
    isNewRefresh: false
    # Code授权码 保存的时间（单位：秒） 默认五分钟
    codeTimeout: 300
    # Access-Token 保存的时间（单位：秒）默认两个小时
    accessTokenTimeout: 7200
    # Refresh-Token 保存的时间（单位：秒） 默认30 天
    refreshTokenTimeout: 2592000
    # Client-Token 保存的时间（单位：秒） 默认两个小时
    clientTokenTimeout: 7200
    # Past-Client-Token 保存的时间（单位：秒） ，默认为-1，代表延续 Client-Token 的有效时间
    pastClientTokenTimeout: 7200
  jwt-secret-key: 




#mybatis-plus的相关依赖
mybatis-plus:
  global-config:
    banner: off #关闭mybatis-plus的启动动画
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
  mapper-locations: classpath:mapper/*.xml

#这里你去gitee申请第三方应用填写即可
gitee:
    client:
      id: 
      Secret: 
    redirect:
      uri: 

wechat:
  app-id: 
  app-secret: 
  redirect-uri: 

captcha:
    email:
      from: xxx<xx@xx.com>
      password:  # 这里我随便填的
      host: smtp.163.com
      port: 465
      user: xxx@163.com
      expire-time: 300 # 300秒

qq:
  app-id: 
  app-key: 
  redirect-uri: 



# 腾讯云短信服务配置
sms-config:
  # 腾讯云账户密钥对 secretId 和 secretKey
  secretId: 
  secretKey: 
  # 短信应用appId和appKey
  appId: 
  appKey: 
  # 签名
  smsSign: 
  # 过期时间
  expireTime: 6  # 6min
  # redis存储前缀
  phonePrefix: captcha-sms-
  # 模板id
  templateIds:
    code:
      login: 
      register: 
